//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.RepairParts = new HashSet<RepairParts>();
            this.Services = new HashSet<Services>();
        }
    
        public int IDrequest { get; set; }
        public int ClientID { get; set; }
        public int StatusID { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int DeviceType { get; set; }
        public int Cost { get; set; }
        public int ReceiverID { get; set; }
        public string IMEI_SN { get; set; }
        public string Model { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual DeviseTypes DeviseTypes { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual RepairTeam RepairTeam { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepairParts> RepairParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Services> Services { get; set; }
    }
}
