//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMC.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class Requests:INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.Request_RepairParts = new HashSet<Request_RepairParts>();
            this.Requests_Services = new HashSet<Requests_Services>();
        }

        private int cost;
        public int IDrequest { get; set; }
        public int ClientID { get; set; }
        public int StatusID { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> DeviceType { get; set; }
        public int Cost {
            get { return cost; }
            set
            {
                cost = value;
                OnPropertyChanged();
            }
        }
        public Nullable<int> ReceiverID { get; set; }
        public string IMEI_SN { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<int> MasterID { get; set; }
        public string Notes { get; set; }
        public string DetectedMulfunction { get; set; }
        public string Appearance { get; set; }
        public string Address { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual DeviseTypes DeviseTypes { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Employees Employees1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_RepairParts> Request_RepairParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requests_Services> Requests_Services { get; set; }
        public virtual Status Status { get; set; }

        public event PropertyChangedEventHandler? PropertyChanged;
        public void OnPropertyChanged([CallerMemberName] string prop = "")
        {
            if (PropertyChanged != null)
                PropertyChanged(this, new PropertyChangedEventArgs(prop));
        }
    }
}
