//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.Request_RepairParts = new HashSet<Request_RepairParts>();
            this.Requests_Services = new HashSet<Requests_Services>();
        }
    
        public int IdRequest { get; set; }
        public int ClientId { get; set; }
        public int StatusId { get; set; }
        public string Reason { get; set; }
        public System.DateTime Date { get; set; }
        public string DetectedMulfunction { get; set; }
        public Nullable<int> MasterId { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public double Cost { get; set; }
        public string Device { get; set; }
        public string IMEI_SN { get; set; }
        public string Appearance { get; set; }
        public bool Type { get; set; }
        public string Address { get; set; }
        public string Notes { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_RepairParts> Request_RepairParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requests_Services> Requests_Services { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
