//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests_Services
    {
        public int RequestID { get; set; }
        public int ServiceID { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Requests Requests { get; set; }
        public virtual Services Services { get; set; }
    }
}
